app_env: 'local'
port: 3000

database:
  type: 'postgres'
  host: 'localhost'
  port: '5432'
  username: 'postgres'
  password: 'Supersecret123'
  db_name: 'dbtest'

microservice:
  uris:
    - 'amqp://localhost:5672'
  queue: 'app_queue'
  auto_ack: true
  multiline:

auth:
  userPoolId: ap-southeast-1_z1Sv7uZjk
  clientId: 72ne78n24vv61o0416j7qanbt3
  region: ap-southeast-1

clients:
  demo_service:
    uris:
      - 'amqp://localhost:5672'
    queue: 'demo_app_queue'
